### ISSUE TITLE
lsif-typescript: umbrella issue

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/scip-typescript#52]
Me and @varungandhi-src have paired on an experiment to implement a fresh lsif-node indexer that emits LSIF typed directly. Early results indicate that this approach might be promising. A rough overview of items we want to validate before committing to this rewrite:

- [x] rough navigation within a local file
- [x] accurate symbol role for definitions
- [x] testing infrastructure
- [x] hover messages
- [x] cross-file navigation
- [x] shorthand syntax
- [x] cross-repo navigation
- [x] yarn workspaces
- [x] import nodes
- [x] #55
- [x] #46 
- [x] composite projects with source maps
- [x] release lsif-node rewrite to npm
- [x] merge lsif typed->graph cli tool
- [x] sourcegraph/sourcegraph#31169
- [x] #56
- [x] WONTFIX method overloading (static and non-static methods with same names)
- [x] #54
- [x] #53

**Comment by olafurpg** [comment]
Close this issue as superseded by the 1) fixed issues and 2) open sub-issues
